version: '3.8'

services:

  bot:
    restart: always
    build: .
    container_name: sharky_bot
    depends_on:
      - db
    environment:
      - MONGO_USER=sharky
      - MONGO_PASS=changeme
      - PROD_TOKEN=changeme


  db:
    restart: always
    image: mongo:latest
    container_name: sharky_db
    volumes:
      - sharky_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sharky
      - MONGO_INITDB_ROOT_PASSWORD=changeme

volumes:
  sharky_db: